export type RetestDemoRecommendation = "RETEST" | "DON'T RETEST";

export type RetestDemoEvent = {
  sno: number;
  deviceId: string;
  failureEvent: number;
  failTest: string;
  failBin: number;
  waferId: string;
  ateSite: number;
  voltageV: number;
  temperatureC: number;
  pRetestBeneficial: number;
  aiRecommendation: RetestDemoRecommendation;
};

/** Presentation rows styled after the Retest AI Agent RETEST events table. */
export const RETEST_DEMO_EVENTS: RetestDemoEvent[] = [
  {
    sno: 1,
    deviceId: "DEV008",
    failureEvent: 1,
    failTest: "Scan_203",
    failBin: 27,
    waferId: "W001",
    ateSite: 8,
    voltageV: 0.85,
    temperatureC: 25,
    pRetestBeneficial: 0.9177,
    aiRecommendation: "RETEST",
  },
  {
    sno: 2,
    deviceId: "DEV056",
    failureEvent: 4,
    failTest: "Scan_151",
    failBin: 23,
    waferId: "W003",
    ateSite: 4,
    voltageV: 0.9,
    temperatureC: 85,
    pRetestBeneficial: 0.9599,
    aiRecommendation: "RETEST",
  },
  {
    sno: 3,
    deviceId: "DEV045",
    failureEvent: 3,
    failTest: "Func_108",
    failBin: 12,
    waferId: "W005",
    ateSite: 5,
    voltageV: 0.88,
    temperatureC: 60,
    pRetestBeneficial: 0.849,
    aiRecommendation: "RETEST",
  },
  {
    sno: 4,
    deviceId: "DEV012",
    failureEvent: 2,
    failTest: "MBIST_03",
    failBin: 31,
    waferId: "W002",
    ateSite: 10,
    voltageV: 0.83,
    temperatureC: 30,
    pRetestBeneficial: 0.9021,
    aiRecommendation: "RETEST",
  },
  {
    sno: 5,
    deviceId: "DEV033",
    failureEvent: 1,
    failTest: "Scan_088",
    failBin: 19,
    waferId: "W001",
    ateSite: 2,
    voltageV: 0.92,
    temperatureC: 25,
    pRetestBeneficial: 0.7812,
    aiRecommendation: "DON'T RETEST",
  },
  {
    sno: 6,
    deviceId: "DEV071",
    failureEvent: 4,
    failTest: "Func_220",
    failBin: 41,
    waferId: "W004",
    ateSite: 7,
    voltageV: 0.95,
    temperatureC: 35,
    pRetestBeneficial: 0.9344,
    aiRecommendation: "RETEST",
  },
  {
    sno: 7,
    deviceId: "DEV019",
    failureEvent: 2,
    failTest: "Scan_045",
    failBin: 15,
    waferId: "W003",
    ateSite: 3,
    voltageV: 0.87,
    temperatureC: 20,
    pRetestBeneficial: 0.6688,
    aiRecommendation: "DON'T RETEST",
  },
  {
    sno: 8,
    deviceId: "DEV062",
    failureEvent: 3,
    failTest: "MBIST_11",
    failBin: 28,
    waferId: "W005",
    ateSite: 9,
    voltageV: 0.91,
    temperatureC: 85,
    pRetestBeneficial: 0.8915,
    aiRecommendation: "RETEST",
  },
  {
    sno: 9,
    deviceId: "DEV004",
    failureEvent: 1,
    failTest: "Func_055",
    failBin: 22,
    waferId: "W002",
    ateSite: 1,
    voltageV: 0.84,
    temperatureC: 40,
    pRetestBeneficial: 0.5523,
    aiRecommendation: "DON'T RETEST",
  },
  {
    sno: 10,
    deviceId: "DEV088",
    failureEvent: 4,
    failTest: "Scan_312",
    failBin: 36,
    waferId: "W001",
    ateSite: 6,
    voltageV: 0.89,
    temperatureC: 55,
    pRetestBeneficial: 0.9456,
    aiRecommendation: "RETEST",
  },
  {
    sno: 11,
    deviceId: "DEV027",
    failureEvent: 2,
    failTest: "Scan_167",
    failBin: 18,
    waferId: "W004",
    ateSite: 8,
    voltageV: 0.86,
    temperatureC: 25,
    pRetestBeneficial: 0.8127,
    aiRecommendation: "RETEST",
  },
  {
    sno: 12,
    deviceId: "DEV041",
    failureEvent: 3,
    failTest: "Func_091",
    failBin: 29,
    waferId: "W003",
    ateSite: 5,
    voltageV: 0.93,
    temperatureC: 70,
    pRetestBeneficial: 0.6011,
    aiRecommendation: "DON'T RETEST",
  },
  {
    sno: 13,
    deviceId: "DEV015",
    failureEvent: 1,
    failTest: "MBIST_07",
    failBin: 33,
    waferId: "W005",
    ateSite: 4,
    voltageV: 0.88,
    temperatureC: 30,
    pRetestBeneficial: 0.8764,
    aiRecommendation: "RETEST",
  },
  {
    sno: 14,
    deviceId: "DEV053",
    failureEvent: 4,
    failTest: "Scan_099",
    failBin: 14,
    waferId: "W002",
    ateSite: 11,
    voltageV: 0.9,
    temperatureC: 45,
    pRetestBeneficial: 0.7239,
    aiRecommendation: "DON'T RETEST",
  },
  {
    sno: 15,
    deviceId: "DEV066",
    failureEvent: 2,
    failTest: "Func_144",
    failBin: 25,
    waferId: "W001",
    ateSite: 2,
    voltageV: 0.85,
    temperatureC: 60,
    pRetestBeneficial: 0.9288,
    aiRecommendation: "RETEST",
  },
  {
    sno: 16,
    deviceId: "DEV039",
    failureEvent: 3,
    failTest: "Scan_278",
    failBin: 37,
    waferId: "W004",
    ateSite: 7,
    voltageV: 0.94,
    temperatureC: 85,
    pRetestBeneficial: 0.8891,
    aiRecommendation: "RETEST",
  },
];
